{% set name = "langchain-postgres" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/langchain_postgres-{{ version }}.tar.gz
  sha256: 3e6f862dfa202df7f671edb987650901786d6e1458a019fcc8d0d9c08fdee8f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - asyncpg >=0.30.0
    - langchain-core >=1.2.11,<2.0
    - pgvector-python >=0.2.5,<0.4
    - psycopg >=3,<4
    - psycopg-pool >=3.2.1,<4
    - sqlalchemy >=2,<3
    - greenlet  # sqlalchemy[asyncio] extra
    - numpy >=1.21,<3

test:
  imports:
    - langchain_postgres
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/langchain-ai/langchain-postgres
  summary: An integration package connecting Postgres and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
